FROM fedora:27
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
RUN dnf --enablerepo=updates-testing -y update
RUN dnf --enablerepo=updates-testing -y install \
    gcc \
    glib2-devel \
    gtk-doc \
    libgudev-devel \
    meson \
    umockdev-devel \
    rpm-build \
    redhat-rpm-config \
    systemd-devel

RUN mkdir /src
WORKDIR /src

