## -*- mode: dockerfile -*-
FROM fedora:34
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
RUN dnf --enablerepo=updates-testing -y update
RUN dnf --enablerepo=updates-testing -y install \
    clang-analyzer \
    codespell \
    gcc \
    git \
    glib2-devel \
    glibc-langpack-en \
    gtk-doc \
    lcov \
    libgudev-devel \
    meson-0.56.2-2.fc34 \
    polkit-devel \
    python3 \
    python3-dbus \
    python3-dbusmock \
    python3-gobject \
    rpm-build \
    redhat-rpm-config \
    systemd-devel \
    umockdev-devel \
    uncrustify

RUN mkdir /src /build
WORKDIR /src
