# https://packit.dev/docs/configuration/

specfile_path: bolt.spec

synced_files:
    - bolt.spec
    - .packit.yaml

upstream_package_name: bolt
downstream_package_name: bolt

copy_upstream_release_description: true

actions:
  get-current-version: bash -c "git describe --tags --abbrev=0 | sed 's|v||'"

jobs:
- job: propose_downstream
  trigger: release
  dist_git_branches:
    - fedora-all
- job: koji_build
  trigger: commit
  dist_git_branches:
    - fedora-all
- job: bodhi_update
  trigger: commit
  dist_git_branches:
    - fedora-stable # rawhide updates are created automatically
